[package]
name = "shared"
version = "0.1.0"
authors = ["Arjan de Pooter <mail@arjandepooter.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"